import { readFileSync } from 'node:fs';
import { neon } from '@neondatabase/serverless';
const all = ['.env','.env.local'].map(f=>{try{return readFileSync(f,'utf8')}catch{return ''}}).join('\n');
const sql = neon(/DATABASE_URL\s*=\s*"?([^"\n]+)"?/.exec(all)[1].trim());
const l = await sql`SELECT "id","grade","manualGrade","updatedAt" FROM "Lead" WHERE "id"='1000438542'`;
console.log('lead now:', JSON.stringify(l[0]));
const gc = await sql`SELECT COUNT(*)::int n FROM "GradeChange" WHERE "changedBy"='system: regrade'`;
console.log('GradeChange rows written by regrade:', gc[0].n);
const ac = await sql`SELECT COUNT(*)::int n FROM "Activity" WHERE "metadata"::text LIKE '%scripts/regrade.mjs%'`;
console.log('Activity rows written by regrade:', ac[0].n);
