-- CreateTable
CREATE TABLE "Lead" (
    "id" TEXT NOT NULL,
    "propertyId" TEXT NOT NULL,
    "addressStreet" TEXT NOT NULL,
    "addressCity" TEXT NOT NULL,
    "addressState" TEXT NOT NULL DEFAULT 'NJ',
    "addressZip" TEXT NOT NULL,
    "addressCounty" TEXT,
    "addressFull" TEXT,
    "mailStreet" TEXT,
    "mailCity" TEXT,
    "mailState" TEXT,
    "mailZip" TEXT,
    "propertyType" TEXT,
    "propertyUse" TEXT,
    "propertyUseCode" INTEGER,
    "landUse" TEXT,
    "yearBuilt" INTEGER,
    "squareFeet" INTEGER,
    "lotSquareFeet" INTEGER,
    "bedrooms" INTEGER,
    "bathrooms" DOUBLE PRECISION,
    "stories" DOUBLE PRECISION,
    "unitsCount" INTEGER,
    "roomsCount" INTEGER,
    "garage" BOOLEAN,
    "pool" BOOLEAN,
    "deck" BOOLEAN,
    "patio" BOOLEAN,
    "basement" BOOLEAN,
    "airConditioning" BOOLEAN,
    "estimatedValue" DOUBLE PRECISION,
    "assessedValue" DOUBLE PRECISION,
    "lastSaleAmount" DOUBLE PRECISION,
    "lastSaleDate" TEXT,
    "estimatedEquity" DOUBLE PRECISION,
    "openMortgageBalance" DOUBLE PRECISION,
    "lenderName" TEXT,
    "mortgageType" TEXT,
    "owner1LastName" TEXT,
    "owner1FirstName" TEXT,
    "companyName" TEXT,
    "ownerOccupied" BOOLEAN,
    "corporateOwned" BOOLEAN,
    "absenteeOwner" BOOLEAN,
    "investorBuyer" BOOLEAN,
    "vacant" BOOLEAN,
    "preForeclosure" BOOLEAN,
    "foreclosure" BOOLEAN,
    "reo" BOOLEAN,
    "highEquity" BOOLEAN,
    "floodZone" BOOLEAN,
    "floodZoneType" TEXT,
    "hoa" BOOLEAN,
    "latitude" DOUBLE PRECISION,
    "longitude" DOUBLE PRECISION,
    "fips" TEXT,
    "apn" TEXT,
    "recordingDate" TEXT,
    "lastUpdateDate" TEXT,
    "skipTraced" BOOLEAN NOT NULL DEFAULT false,
    "skipTracedAt" TIMESTAMP(3),
    "phone1" TEXT,
    "phone2" TEXT,
    "email1" TEXT,
    "email2" TEXT,
    "engine" INTEGER,
    "renewalTargetDate" TIMESTAMP(3),
    "grade" TEXT,
    "travelersEligible" TEXT,
    "travelersNotes" JSONB,
    "plymouthEligible" TEXT,
    "plymouthNotes" JSONB,
    "lowPremium" DOUBLE PRECISION,
    "expectedPremium" DOUBLE PRECISION,
    "highPremium" DOUBLE PRECISION,
    "pricingConfidence" INTEGER,
    "status" TEXT NOT NULL DEFAULT 'new',
    "producerEmail" TEXT,
    "posQuoteNumber" TEXT,
    "posCarrier" TEXT,
    "boundPremium" DOUBLE PRECISION,
    "boundDate" TIMESTAMP(3),
    "authorizationDate" TIMESTAMP(3),
    "rawData" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Lead_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Activity" (
    "id" TEXT NOT NULL,
    "leadId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "metadata" JSONB,
    "createdBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Activity_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Lead_propertyId_key" ON "Lead"("propertyId");

-- AddForeignKey
ALTER TABLE "Activity" ADD CONSTRAINT "Activity_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
